### ISSUE TITLE
支持vue3么？

### ISSUE THREAD

**Issue by songyu719** [kirillmurashov/vue-drag-resize#101]
支持vue3么？

**Comment by kirillmurashov** [comment]
I'm working on it, a vue3 compatible version will be released today or tomorrow

**Comment by kirillmurashov** [comment]
The component code has been greatly improved, 
I have released version 1.5.1 for Vue2 and version 2.0.0 for Vue3

Please use "npm i -s vue-drag-resize@next" for use in Vue3

The vue3 branch has completely rewritten the demo using the composition API. For examples of how to use it, go there
