### ISSUE TITLE
Support for vue 3?

### ISSUE THREAD

**Issue by kolaente** [kirillmurashov/vue-drag-resize#102]
Hey there, are there any plans to provide support for vue 3?

**Comment by kirillmurashov** [comment]
I'm working on it, a vue3 compatible version will be released today or tomorrow

**Comment by kirillmurashov** [comment]
The component code has been greatly improved, 
I have released version 1.5.1 for Vue2 and version 2.0.0 for Vue3

Please use "npm i -s vue-drag-resize@next" for use in Vue3

The vue3 branch has completely rewritten the demo using the composition API. For examples of how to use it, go there

**Comment by kolaente** [comment]
Awesome, thanks!
