### ISSUE TITLE
send data in resize event

### ISSUE THREAD

**Issue by msadeghyan1996** [kirillmurashov/vue-drag-resize#104]
hi. i need send custom data in resize event and check data in function for save newRect for that.
how can i do this?

**Comment by msadeghyan1996** [comment]
i fixed that with below code :
```@resizing="resize, resizeType='widget1'"```
but i thing it's not good way!

**Comment by msadeghyan1996** [comment]
i fixed it with @activated event and set $resizeType to 'widget1' but i think this way not be correct

**Comment by pinkcao** [comment]
it's about vue
maybe you want the way as follows

@resize="functionA($event, index)"
here, the $event means the params in this.$emit('functionA', newRect)

write as so in methods:
methods: {
    functionA(newRect, index) {
        console.log(newRect)
        console.log(index)
    }
}
