### ISSUE TITLE
When I put the data in the state of page, set data not work

### ISSUE THREAD

**Issue by Thlq** [kirillmurashov/vue-drag-resize#110]
![image](https://user-images.githubusercontent.com/21211777/116333921-f2b2b400-a806-11eb-8c7e-1f787702b414.png)
![image](https://user-images.githubusercontent.com/21211777/116333957-fd6d4900-a806-11eb-9cc3-c046448011b9.png)
![image](https://user-images.githubusercontent.com/21211777/116333969-03fbc080-a807-11eb-977b-967df14764ee.png)

**Comment by Thlq** [comment]
resolved， thanks

**Comment by kevingrevillot** [comment]
Hello, got same issue here

any suggestion ?

**Comment by kirillmurashov** [comment]
Fixed in versions 1.5.3 & 2.0.3
