### ISSUE TITLE
Setting auto width and height is invalid

### ISSUE THREAD

**Issue by hinet** [kirillmurashov/vue-drag-resize#115]
`<VueDragResize
              v-for="(item,index) in Elements"
              :key="index"
              :isActive="false"
              :parentLimitation="true"
              :parentScaleX="2"
              :parentScaleY="2"
              :w="item.width || 'auto'"
              :h="item.height || 'auto'"
              ........
             >
            </VueDragResize>`

Setting the width and height property to auto is invalid？

**Comment by kirillmurashov** [comment]
Fixed in v.1.5.4
