### ISSUE TITLE
Issue with setting height/width/x/y programatically

### ISSUE THREAD

**Issue by MrTeapot** [kirillmurashov/vue-drag-resize#125]
Hey!

The issue is reproduced in this codesandbox: https://codesandbox.io/s/vue-drag-resize-issue-pq9kq?file=/src/components/MyBox.vue

Why do I have to press the button four times before it reaches it's desired state? How can I set the height/width/x/y programatically without triggering a bunch of resize events?

**Comment by rsvidevince** [comment]
Hey @MrTeapot did you manage to? I would like to programatically set the size of a container too...
