### ISSUE TITLE
Touch Support

### ISSUE THREAD

**Issue by tylerwiegand** [kirillmurashov/vue-drag-resize#15]
You mention that there is support for touch events -- does this mean I would need to implement touch drag support myself? When I navigate to the demo page and attempt to use my phone or tablet (both iOS devices), the elements get selected but won't move around. Also, the width and height inputs change to NaN instead of the normal pixel size as seen on desktop.

Is this intended for mobile use? I am looking for a library JUST like this but with mobile support. Thanks!

**Comment by kirillmurashov** [comment]
Unfortunately this was a bug, I fixed it

**Comment by tylerwiegand** [comment]
Thanks! I checked on the day you made the change but it hadn't fixed (guessing the demo wasn't changed yet) but it seems to be all good now. Thanks for the quick turnaround!! =)
