### ISSUE TITLE
父元素缩放后，<vue-drag-resize/>元素拖着拖着就不见了是咋回事呢

### ISSUE THREAD

**Issue by peachapp** [kirillmurashov/vue-drag-resize#186]
父元素放大后，拖着拖着就不见了，这是啥情况呢，有没有朋友遇到过这个问题呀

https://github.com/kirillmurashov/vue-drag-resize/assets/26792399/4709d6e0-dcf2-4745-ba91-080a31580009

**Comment by Raywh** [comment]
1. 有没有可能是层级不对？
2. 父元素的缩放 过大 或者过小？
3. 缩放比例 互相影响

**Comment by peachapp** [comment]
> 1. 有没有可能是层级不对？
> 2. 父元素的缩放 过大 或者过小？
> 3. 缩放比例 互相影响
我也不清楚咋回事，莫名奇妙的又好了

**Comment by Raywh** [comment]
你这个推荐使用 canvas库 fabric.js
http://fabricjs.com/
复杂的元素拖拽

**Comment by AKclown** [comment]
遇到相同问题，放大   :parentScaleX="scaleValue / 100"  之后，拖到视图中间，会被定位到最侧边
                    :parentScaleY="scaleValue / 100"
