### ISSUE TITLE
Strange behavior in modal

### ISSUE THREAD

**Issue by shchegol** [kirillmurashov/vue-drag-resize#2]
I tried to use component in the bootstrap modal. The component behaved strangely. An axis show minus values when dragging.

...
I found out that is due to the visibility of the component.

**Comment by TitanFighter** [comment]
I do not know regarding modal, but I had this issue in case of using `<div class="col">` (or `<v-col>` in case of using "bootstrap-vue"), which by default has `position: relative`. `position: static` (or `class="position-static"` in case of bootstrap) fixed the problem.

**Comment by shchegol** [comment]
Unfortunately not work for me. I made custom invisible but not "display: none" modal and all work fine.

**Comment by TitanFighter** [comment]
@shchegol Im pretty sure without demo no one can help you. You can take for example [this code](https://codesandbox.io/s/lprlwjy9vz), as a basis, and show where the trouble is. Then I can check if I can help you.
