### ISSUE TITLE
Example from the README does not work

### ISSUE THREAD

**Issue by TitanFighter** [kirillmurashov/vue-drag-resize#3]
[Here is the code](https://codesandbox.io/s/kkln63y27o) from the readme in a sandbox.
Move it a bit and you will see the problem. The same strange behavior I have in my project.

I use VueJS 2.5.16.

Any ideas?
Thanks.

**Comment by kirillmurashov** [comment]
Body and app dimensions must not be zero;
E.g.:
`body{
				width: 500px;
				height: 500px;
			}
			#app{
				position:relative;
				width: 100%;
				height: 100%;
			}`

**Comment by TitanFighter** [comment]
It was stupid :) Thank you!
