### ISSUE TITLE
Based on the docs "parentLimitation" by default is "false", but in reality is "true"

### ISSUE THREAD

**Issue by TitanFighter** [kirillmurashov/vue-drag-resize#4]
In order to drag element out of parent it is necessary to explicitly set ":parentLimitation="false", however according to the docs the default value already should be "false"
```
parentLimitation
Type: Boolean
Required: false
Default: false

Limits the scope of the component's change to its parent size.
```

https://github.com/kirillmurashov/vue-drag-resize/blob/master/src/components/vue-drag-resize.js#L19

**Comment by kirillmurashov** [comment]
Yes, thanks, fixed to false
