### ISSUE TITLE
Support for 'vw' units instead of 'px'

### ISSUE THREAD

**Issue by nelsonad** [kirillmurashov/vue-drag-resize#52]
Would it be possible to add support for 'vw' units for the top/left calculations instead of 'px'?

With pixel's the locations of the elements do not scale as the browser window changes, support for vw positioning would solve this issue.

**Comment by nelsonad** [comment]
I tried modifying the code and simple updating 'px' instances to 'vw' but this did not work immediately as small mouse movements would result in large changes..so some kind of calculation/conversion will be required i think

**Comment by timpulver** [comment]
Would be good to have `%` as well.

**Comment by nelsonad** [comment]
I was able to do get what I needed by doing a conversion to vw outside of vue-drag-resize pretty easily. Closing the issue.
