### ISSUE TITLE
Most recent code not available through npm

### ISSUE THREAD

**Issue by pxlrbt** [kirillmurashov/vue-drag-resize#59]
Last recent version of vue-drag-resize is 1.3.2. But this version does not contain the snapToGrid feature which is documented in the docs. Could you release a new version with most up to date code?

**Comment by nick-running** [comment]
Yeah,please update your newest version code,add snapToGrid feature to it.

**Comment by kolaente** [comment]
@kirillmurashov Could you please publish the new version?

**Comment by ferrinweb** [comment]
Today is April 1, 2020, and April Fool's Day, is this reponsitory abandoned?

**Comment by kirillmurashov** [comment]
fix
