### ISSUE TITLE
aspectRatio has some problems

### ISSUE THREAD

**Issue by JasonWong-ZS** [kirillmurashov/vue-drag-resize#61]
The height or width is negative, when I set aspectRatio equal to true and action is tl or the action is tr or the action is bl or the action is br

**Comment by 18402025768** [comment]
Invalid prop: custom validator check failed for prop "w"

**Comment by 18402025768** [comment]
Invalid prop: custom validator check failed for prop "h".

**Comment by 18402025768** [comment]
just so

**Comment by geniyangge** [comment]
Hello, has the problem been solved? I have the same problem now.
