### ISSUE TITLE
When NPM, the component does not have the "snapToGrid" attribute, but it is version 1.3.2

### ISSUE THREAD

**Issue by zjhr** [kirillmurashov/vue-drag-resize#65]
When NPM, the component does not exist "snapToGrid,gridX,gridY", but the source code does exist on github.

**Comment by ArhontSL** [comment]
Will this problem be solved?

**Comment by PiccoloYu** [comment]
Yes, I did.

**Comment by zcqno1** [comment]
![image](https://user-images.githubusercontent.com/11766057/63563567-16cee400-c594-11e9-8e5c-223a7e3df1ef.png)
![image](https://user-images.githubusercontent.com/11766057/63563626-40880b00-c594-11e9-901f-2c2780e49823.png)
It seems that there's a long time not to release new version after the v1.3.2 on 29 Jun 2018, though there are some features and fixes from then on.

**Comment by ehhc** [comment]
Is there any hope for a new npm package? :)

**Comment by Alexlg89** [comment]
Bump :)
