### ISSUE TITLE
snapToGrid, gridX and gridY does not work!

### ISSUE THREAD

**Issue by vahiddabbagh** [kirillmurashov/vue-drag-resize#82]
I look at the source code at npm and I could not even find the props and methods about grid!
Please update the npm src with the correct one in github
Thanks for your great package

**Comment by wwangruigang** [comment]
怎么解决?

**Comment by kybetter** [comment]
文档里面就没有写 grid

**Comment by Reviewlike** [comment]
代码拉下来但是启动不了，你们能启动吗

**Comment by kybetter** [comment]
别用这个，用另外一个：https://github.com/mauricius/vue-draggable-resizable

**Comment by kirillmurashov** [comment]
Updated and working, updated documentation
