### ISSUE TITLE
onDragstop is not triggered on the mobile end

### ISSUE THREAD

**Issue by NEIGHT-Wind** [kirillmurashov/vue-drag-resize#89]
Are you sure this binding event can be bound？

in components/vue-drag-resize.js - line209

I use drag on the mobile end. onDragstop is not triggered at the end of the drag. It will be triggered when I click again.

So I looked at the source code and found that the touchend event was not triggered, this.up There was no enforcement

**Comment by kirillmurashov** [comment]
fixed it in version 1.4.2
