### ISSUE TITLE
auto for initial width and height

### ISSUE THREAD

**Issue by dkjain** [kirillmurashov/vue-drag-resize#97]
This is a request to add support for `auto` for `w` prop (initial width) and `auto` for `h` (initial height)

**Comment by el-schneider** [comment]
I would also like to see this!

**Comment by arpit-uno** [comment]
@kirillmurashov any update on this. Can we expect this in near future?

**Comment by kirillmurashov** [comment]
Hi,@arpit-uno, thanks so much for the donation !
Yes, there are plans to add several features including this one. I hope to implement it in the next few weeks.

**Comment by kirillmurashov** [comment]
New release for vue2 and vue3 with support for this feature
